
import { GoogleGenAI, Modality } from "@google/genai";

// FIX: Initialize with object and remove non-null assertion.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const getFocusTip = async (sessionTitle: string): Promise<string> => {
  try {
    const prompt = `Proporciona un consejo corto, alentador y útil para alguien que está a punto de tomar una clase de ${sessionTitle}. El consejo debe estar en español, ser sobre un enfoque físico o mental específico y tener menos de 25 palabras. Por ejemplo: 'Concéntrate en la activación de tu core con cada respiración para maximizar la estabilidad.'`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    
    return response.text;
  } catch (error) {
    console.error("Error fetching focus tip from Gemini API:", error);
    return `¡Disfruta de tu clase de ${sessionTitle}! Concéntrate en tu respiración y escucha a tu cuerpo.`;
  }
};

// FIX: Add 'editImageWithPrompt' to handle image editing requests.
export const editImageWithPrompt = async (
  base64ImageData: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    throw new Error('No image was generated by the API.');
  } catch (error) {
    console.error("Error editing image with Gemini API:", error);
    throw new Error("Failed to edit image. Please try again.");
  }
};
